all: true
include:
  - "src/**/*.js"
  - "src/**/*.ts"
exclude:
  - "**/*.test.js"
  - "**/*.test.ts"
extension:
  - ".ts"
  - ".tsx"
require:
  -  "ts-node/register"
reporter:
  - "text-summary"
  - "text"